-- MySQL Script generated by MySQL Workbench
-- 10/19/16 18:02:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema usappyas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usappyas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usappyas` DEFAULT CHARACTER SET utf8 ;
USE `usappyas` ;

-- -----------------------------------------------------
-- Table `usappyas`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`car` (
  `car_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '代車ID',
  `sscode` VARCHAR(6) NULL DEFAULT NULL COMMENT '管理SSコード',
  `car_name` VARCHAR(50) NOT NULL COMMENT '車種名称',
  `plate_no` VARCHAR(4) NOT NULL COMMENT '車番',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`car_id`),
  INDEX `index_car01` (`sscode` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '車両';


-- -----------------------------------------------------
-- Table `usappyas`.`car_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`car_reservation` (
  `reservation_no` VARCHAR(14) NOT NULL COMMENT '予約番号',
  `car_id` INT(11) NOT NULL COMMENT '代車ID',
  `start_time` DATETIME NOT NULL COMMENT '開始日時',
  `end_time` DATETIME NOT NULL COMMENT '終了日時',
  `sscode` VARCHAR(6) NOT NULL COMMENT '利用SSコード',
  `member_id` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Usappy会員ID',
  `card_no` VARCHAR(16) NULL DEFAULT NULL COMMENT '掛カード番号',
  `purpose_code` VARCHAR(10) NULL DEFAULT NULL COMMENT '目的コード',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '作成日時',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`reservation_no`),
  INDEX `car_id` (`car_id` ASC),
  INDEX `index_car_reservation01` (`sscode` ASC),
  CONSTRAINT `car_reservation_ibfk_1`
    FOREIGN KEY (`car_id`)
    REFERENCES `usappyas`.`car` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '代車予約';


-- -----------------------------------------------------
-- Table `usappyas`.`enable_coating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`enable_coating` (
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `coating_code` VARCHAR(20) NOT NULL COMMENT 'コーティングコード',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`sscode`, `coating_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '取扱コーティング';


-- -----------------------------------------------------
-- Table `usappyas`.`menu_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`menu_setting` (
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `menu_code` VARCHAR(20) NOT NULL COMMENT 'メニューコード : oil: オイル交換 tire: タイヤ交換 inspection wash: 洗車 coating: コーティング other: その他',
  `max_parallel_count` INT(11) NULL DEFAULT NULL COMMENT '同時実施可能数',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`sscode`, `menu_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '作業メニュー設定';


-- -----------------------------------------------------
-- Table `usappyas`.`open_timer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`open_timer` (
  `open_timer_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '受付時間タイマーID',
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `menu_code` VARCHAR(20) NOT NULL COMMENT 'メニューコード : oil: オイル交換 tire: タイヤ交換 inspection wash: 洗車 coating: コーティング other: その他',
  `is_holiday` TINYINT(4) NOT NULL COMMENT '土日祝祭日フラグ',
  `start_date` DATE NULL DEFAULT NULL COMMENT '切替開始日',
  `end_date` DATE NULL DEFAULT NULL COMMENT '切替終了日',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`open_timer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '受付時間タイマー';


-- -----------------------------------------------------
-- Table `usappyas`.`open_timer_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`open_timer_detail` (
  `open_timer_id` INT(10) UNSIGNED NOT NULL COMMENT '受付時間タイマーID',
  `start_time` INT(11) NOT NULL COMMENT '開始時刻 : 00:00を0とする分で表現\n\n00:00 -> 0\n24:00 -> 1440',
  `end_time` INT(11) NOT NULL COMMENT '終了時刻 : 00:00を0とする分で表現\n\n00:00 -> 0\n24:00 -> 1440',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '受付時間タイマー詳細';


-- -----------------------------------------------------
-- Table `usappyas`.`repaire_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repaire_staff` (
  `repair_staff_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'リペアスタッフID',
  `branch_code` VARCHAR(6) NOT NULL COMMENT '所属支店コード',
  `staff_name` VARCHAR(50) NOT NULL COMMENT 'スタッフ氏名',
  `login_id` VARCHAR(30) NOT NULL COMMENT 'ログインID',
  `password` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'パスワード',
  `piece_count` INT(11) NULL DEFAULT NULL COMMENT '基本対応可能ピース数',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'リペアスタッフステータス : 0:有効 1:無効(ログイン不可)',
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '作成日時',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`repair_staff_id`),
  UNIQUE INDEX `login_id` (`login_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペアスタッフ';


-- -----------------------------------------------------
-- Table `usappyas`.`pice_count`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`pice_count` (
  `repair_staff_id` INT(10) UNSIGNED NOT NULL COMMENT 'リペアスタッフID',
  `year` INT(11) NOT NULL COMMENT '年',
  `month` INT(11) NOT NULL COMMENT '月',
  `piece_count` INT(11) NOT NULL COMMENT '月別対応可能ピース数',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`repair_staff_id`, `year`, `month`),
  CONSTRAINT `pice_count_ibfk_1`
    FOREIGN KEY (`repair_staff_id`)
    REFERENCES `usappyas`.`repaire_staff` (`repair_staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '月別ピース数';


-- -----------------------------------------------------
-- Table `usappyas`.`pit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`pit` (
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `pit_no` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ピットNo. : SSコード毎の連番',
  `pit_name` VARCHAR(50) NOT NULL COMMENT 'ピット名',
  `note` TEXT NULL DEFAULT NULL COMMENT '備考',
  `is_public` TINYINT(4) NOT NULL DEFAULT '1' COMMENT 'ネット予約対象フラグ',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`sscode`, `pit_no`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '作業ピット';


-- -----------------------------------------------------
-- Table `usappyas`.`pit_enable_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`pit_enable_menu` (
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `pit_no` INT(10) UNSIGNED NOT NULL COMMENT 'ピットNo. : SSコード毎の連番',
  `menu_code` VARCHAR(20) NOT NULL COMMENT 'メニューコード : oil: オイル交換 tire: タイヤ交換 inspection wash: 洗車 coating: コーティング other: その他',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`sscode`, `pit_no`, `menu_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'ピット作業可能メニュー';


-- -----------------------------------------------------
-- Table `usappyas`.`repair_event_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repair_event_plan` (
  `event_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'イベントID',
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `start_date` DATE NOT NULL COMMENT 'イベント開始日',
  `end_date` DATE NOT NULL COMMENT 'イベント終了日',
  `event_name` VARCHAR(50) NOT NULL COMMENT 'イベント名',
  `piece_count` INT(11) NULL DEFAULT NULL COMMENT '目標ピース数',
  `target_sales` INT(11) NOT NULL DEFAULT '0' COMMENT '目標金額',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`event_id`),
  INDEX `index_repare_event_plan01` USING BTREE (`sscode` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペアイベント目標';


-- -----------------------------------------------------
-- Table `usappyas`.`repair_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repair_report` (
  `repair_staff_id` INT(10) UNSIGNED NOT NULL COMMENT 'リペアスタッフID',
  `repair_date` DATE NOT NULL COMMENT 'リペア作業日',
  `work_code` INT(11) NOT NULL COMMENT 'リペア実績出勤区分',
  `weather_code` INT(11) NULL DEFAULT '0' COMMENT '天気コード',
  `sscode1` VARCHAR(6) NOT NULL COMMENT '勤務地SSコード1',
  `sscode2` VARCHAR(6) NULL DEFAULT NULL COMMENT '勤務地SSコード2',
  `start_time` INT(11) NULL DEFAULT NULL COMMENT '勤務開始時刻 : 00:00を0とする分で表現\n\n00:00 -> 0\n24:00 -> 1440',
  `end_time` INT(11) NULL DEFAULT NULL COMMENT '勤務終了時刻 : 00:00を0とする分で表現\n\n00:00 -> 0\n24:00 -> 1440',
  `rest_min` INT(11) NULL DEFAULT '0' COMMENT '休憩時間(分)',
  `work_min` INT(11) NULL DEFAULT '0' COMMENT '施工時間(分)',
  `car_count` INT(11) NULL DEFAULT '0' COMMENT '車台数',
  `rule_piece_count` INT(11) NULL DEFAULT '0' COMMENT 'ルールピース数',
  `sales_piece_count` INT(11) NULL DEFAULT NULL COMMENT '売上ピース数',
  `price` INT(11) NULL DEFAULT '0' COMMENT '金額',
  `cancel_count` INT(11) NULL DEFAULT '0' COMMENT 'キャンセル数',
  `cancel_price` INT(11) NULL DEFAULT '0' COMMENT 'キャンセル金額',
  `cost_price` INT(11) NULL DEFAULT '0' COMMENT '資材発注金額',
  `note` VARCHAR(30) NULL DEFAULT NULL COMMENT '備考',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`repair_staff_id`, `repair_date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペア実績';


-- -----------------------------------------------------
-- Table `usappyas`.`repair_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repair_reservation` (
  `reservation_no` VARCHAR(14) NOT NULL COMMENT '予約番号',
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `a_piece_count` INT(11) NOT NULL DEFAULT '0' COMMENT 'A:キズピース数',
  `b_piece_count` INT(11) NOT NULL DEFAULT '0' COMMENT 'B:へこみピース数',
  `arrival_time` DATETIME NULL DEFAULT NULL COMMENT '入庫予定日時',
  `return_time` DATETIME NULL DEFAULT NULL COMMENT '納車予定日時',
  `member_id` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Usappy会員ID',
  `card_no` VARCHAR(16) NULL DEFAULT NULL COMMENT '掛カード番号',
  `repair_staff_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'リペアスタッフID',
  `price` INT(11) NOT NULL COMMENT '金額',
  `plate_no` VARCHAR(4) NULL DEFAULT NULL COMMENT '車番',
  `car_maker_code` INT(11) NULL DEFAULT NULL COMMENT '車両メーカーコード',
  `car_model_code` INT(11) NULL DEFAULT NULL COMMENT '車両モデルコード',
  `car_type_code` INT(11) NULL DEFAULT NULL COMMENT '車両型式コード',
  `car_year` INT(11) NULL DEFAULT NULL COMMENT '車両登録年式',
  `car_month` INT(11) NULL DEFAULT NULL COMMENT '車両登録月',
  `car_grade_code` INT(11) NULL DEFAULT NULL COMMENT '車両グレードコード',
  `car_color_code` INT(11) NULL DEFAULT NULL COMMENT '車両色コード',
  `is_car_request` TINYINT(4) NULL DEFAULT NULL COMMENT '代車要望フラグ : 0:なし\n\n1:あり',
  `is_shuttle_request` TINYINT(4) NULL DEFAULT NULL COMMENT '送迎有無',
  `color_number` VARCHAR(10) NULL DEFAULT NULL COMMENT 'カラーナンバー',
  `image_keys_json` TEXT NULL DEFAULT NULL COMMENT '画像キー配列JSON',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '作業ステータス : 0:実施待ち 1:完了　2:キャンセル(現在未使用)',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`reservation_no`),
  INDEX `index_reservation01` (`sscode` ASC),
  INDEX `index_reservation02` (`created_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペア作業予約';


-- -----------------------------------------------------
-- Table `usappyas`.`repair_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repair_schedule` (
  `repair_schedule_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'リペアスケジュールID',
  `repair_staff_id` INT(10) UNSIGNED NOT NULL COMMENT 'リペアスタッフID',
  `start_time` DATETIME NOT NULL COMMENT '配置開始日時',
  `end_time` DATETIME NOT NULL COMMENT '配置終了日時',
  `sscode` VARCHAR(6) NULL DEFAULT NULL COMMENT 'SSコード',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`repair_schedule_id`),
  INDEX `index_repaire_schedule01` (`sscode` ASC),
  INDEX `repair_schedule_ibfk_1` (`repair_staff_id` ASC),
  CONSTRAINT `repair_schedule_ibfk_1`
    FOREIGN KEY (`repair_staff_id`)
    REFERENCES `usappyas`.`repaire_staff` (`repair_staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペアスケジュール';


-- -----------------------------------------------------
-- Table `usappyas`.`repair_staff_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`repair_staff_plan` (
  `repair_staff_id` INT(10) UNSIGNED NOT NULL COMMENT 'リペアスタッフID',
  `year` INT(10) UNSIGNED NOT NULL COMMENT '目標年',
  `month` INT(11) NOT NULL COMMENT 'リペア目標月',
  `piece_count` INT(11) NOT NULL DEFAULT '0' COMMENT '目標ピース数',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`repair_staff_id`, `year`, `month`),
  CONSTRAINT `repair_staff_plan_ibfk_1`
    FOREIGN KEY (`repair_staff_id`)
    REFERENCES `usappyas`.`repaire_staff` (`repair_staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'リペアスタッフ目標';


-- -----------------------------------------------------
-- Table `usappyas`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`reservation` (
  `reservation_no` VARCHAR(14) NOT NULL COMMENT '予約番号',
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `pit_no` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'ピットNo. : SSコード毎の連番',
  `menu_code` VARCHAR(20) NOT NULL COMMENT 'メニューコード : oil: オイル交換 tire: タイヤ交換 inspection wash: 洗車 coating: コーティング other: その他',
  `menu_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '作業名',
  `arrival_time` DATETIME NULL DEFAULT NULL COMMENT '入庫予定日時',
  `start_time` DATETIME NOT NULL COMMENT '開始日時',
  `end_time` DATETIME NOT NULL COMMENT '終了日時',
  `member_id` VARCHAR(12) NULL DEFAULT NULL COMMENT 'Usappy会員ID',
  `card_no` VARCHAR(16) NULL DEFAULT NULL COMMENT '掛カード番号',
  `plate_no` VARCHAR(4) NOT NULL COMMENT '車番',
  `car_maker_code` INT(11) NULL DEFAULT NULL COMMENT '車両メーカーコード',
  `car_model_code` INT(11) NULL DEFAULT NULL COMMENT '車両モデルコード',
  `car_type_code` INT(11) NULL DEFAULT NULL COMMENT '車両型式コード',
  `car_year` INT(11) NULL DEFAULT NULL COMMENT '車両登録年式',
  `car_month` INT(11) NULL DEFAULT NULL COMMENT '車両登録月',
  `car_grade_code` INT(11) NULL DEFAULT NULL COMMENT '車両グレードコード',
  `car_color_code` INT(11) NULL DEFAULT NULL COMMENT '車両色コード',
  `car_size_code` INT(11) NULL DEFAULT NULL COMMENT '車両サイズコード',
  `car_weight_code` INT(11) NULL DEFAULT NULL COMMENT '車両重量コード',
  `inspection_date` DATE NULL DEFAULT NULL COMMENT '車検満了日',
  `is_car_request` TINYINT(4) NULL DEFAULT NULL COMMENT '代車要望フラグ : 0:なし\n\n1:あり',
  `is_shuttle_request` TINYINT(4) NULL DEFAULT NULL COMMENT '送迎有無',
  `tire_size_code` INT(11) NULL DEFAULT '0' COMMENT 'タイヤサイズコード',
  `tire_preparation_code` TINYINT(4) NULL DEFAULT NULL COMMENT 'タイヤの準備 : 1:購入予定 2:持ち込み',
  `wheel_preparation_code` TINYINT(4) NULL DEFAULT NULL COMMENT 'ホイールの準備 : 1:あり 2:なし',
  `coating_code` VARCHAR(10) NULL DEFAULT NULL COMMENT 'コーティングコード',
  `other_request` TEXT NULL DEFAULT NULL COMMENT 'その他要望など',
  `save_from` VARCHAR(10) NOT NULL DEFAULT 'usappy',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '作業ステータス : 0:実施待ち 1:完了　2:キャンセル(現在未使用)',
  `hashkey` VARCHAR(64) NULL DEFAULT NULL COMMENT 'ハッシュキー',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`reservation_no`),
  INDEX `index_reservation01` (`sscode` ASC),
  INDEX `index_reservation02` (`created_at` ASC),
  INDEX `index_reservation03` (`hashkey` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '作業予約';


-- -----------------------------------------------------
-- Table `usappyas`.`reservation_no`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`reservation_no` (
  `reservation_date` DATETIME NOT NULL COMMENT '予約日付',
  `ident` VARCHAR(1) NOT NULL DEFAULT 'W' COMMENT '識別子 : R: リペア予約 W:リペア以外の予約',
  `seq_no` INT(11) NOT NULL AUTO_INCREMENT COMMENT '番号',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`reservation_date`, `ident`, `seq_no`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '予約番号';


-- -----------------------------------------------------
-- Table `usappyas`.`stop_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usappyas`.`stop_date` (
  `sscode` VARCHAR(6) NOT NULL COMMENT 'SSコード',
  `menu_code` VARCHAR(20) NOT NULL COMMENT 'メニューコード : oil: オイル交換 tire: タイヤ交換 inspection wash: 洗車 coating: コーティング other: その他',
  `stop_date` DATE NOT NULL COMMENT '受付中止日',
  `created_at` DATETIME NOT NULL COMMENT '作成日時',
  `updated_at` DATETIME NOT NULL COMMENT '最終更新日時',
  PRIMARY KEY (`sscode`, `menu_code`, `stop_date`),
  CONSTRAINT `stop_date_ibfk_1`
    FOREIGN KEY (`sscode` , `menu_code`)
    REFERENCES `usappyas`.`menu_setting` (`sscode` , `menu_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '受付中止日';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
